#!/bin/sh

set -e

if [ $# -ne 1 ]; then
  echo "Usage: makesource <release>"
  exit 1
fi

SVNTAGVER=`echo $1 | tr '.' '_'`
SVNPATH="release_$SVNTAGVER"

PACKNAME=fpc-$1.source
OUTPUTDIR=..

rm -rf buildsrc

mkdir buildsrc
cd buildsrc
svn co http://svn.freepascal.org/svn/fpc/tags/$SVNPATH fpc

find -name .svn -type d | xargs tar --remove-files -cvf $OUTPUTDIR/SVNfiles-$1.tar.gz 

rm -f $OUTPUTDIR/$PACKNAME.tar.gz $OUTPUTDIR/$PACKNAME.zip
zip -D9r $OUTPUTDIR/$PACKNAME.zip fpc
tar cfv - fpc/ | gzip > $OUTPUTDIR/$PACKNAME.tar.gz
rm -rf buildsrc
