#!/bin/sh
set -e

if [ $# -eq 1 ]; then
  VERSION=$1
  GITTAGVER=`echo $VERSION | tr '.' '_'`
  GITTAG="release_$GITTAGVER"
elif [ $# -eq 3 ] && [ $1 = "-gittag" ]; then
  GITTAG=$2
  VERSION=$3
else
  echo "Usage: $0 [-gittag <tag>] <release>"
  echo "Examples: $0 -gittag release_3_2_4-branch 3.2.4-rc1"
  echo "          $0 2.2.4"
  exit 1
fi

PACKNAME=fpcbuild-$VERSION
OUTPUTDIR=..

rm -rf buildsrc

mkdir buildsrc
cd buildsrc

rm -f $OUTPUTDIR/$PACKNAME.tar.gz $OUTPUTDIR/$PACKNAME.zip

GITREPO=https://gitlab.com/freepascal.org/fpc/build.git

git clone --depth 1 --recurse-submodules --branch $GITTAG $GITREPO fpcbuild-$VERSION
for repos in fpcbuild-$VERSION fpcbuild-$VERSION/fpcsrc fpcbuild-$VERSION/fpcdocs; do
  CURPATH=`pwd`
  cd $repos
  git config core.eol crlf
  cd $CURPATH
done

cd fpcbuild-$VERSION 
git ls-files -z --recurse-submodules | xargs -0 rm
git checkout . --recurse-submodules
cd ..

for repos in fpcbuild-$VERSION fpcbuild-$VERSION/fpcsrc fpcbuild-$VERSION/fpcdocs; do
  rm -rf $repos/.git
done 
zip -D9r $OUTPUTDIR/$PACKNAME.zip fpcbuild-$VERSION
rm -rf fpcbuild-$VERSION

git clone --depth 1 --recurse-submodules --branch $GITTAG $GITREPO fpcbuild-$VERSION
for repos in fpcbuild-$VERSION fpcbuild-$VERSION/fpcsrc fpcbuild-$VERSION/fpcdocs; do
  rm -rf $repos/.git
done
tar cfv - fpcbuild-$VERSION/ | gzip > $OUTPUTDIR/$PACKNAME.tar.gz

cd ..
rm -rf buildsrc
