#!/bin/sh

set -e

if [ $# -eq 1 ]; then
  VERSION=$1
  SVNTAGVER=`echo $VERSION | tr '.' '_'`
  SVNPATH="tags/release_$SVNTAGVER"
elif [ $# -eq 3 ] && [ $1 = "-svnpath" ]; then
  SVNPATH=$2
  VERSION=$3
else
  echo "Usage: makesource [-svnpath <svnpath>] <release>"
  echo "Examples: makesource -svnpath branches/release_2_2_4_rc1 2.2.4rc1"
  echo "          makesource 2.2.4"
  exit 1
fi

PACKNAME=fpc-$VERSION.source
OUTPUTDIR=..

rm -rf buildsrc

mkdir buildsrc
cd buildsrc
svn co http://svn.freepascal.org/svn/fpc/$SVNPATH fpc

find -name .svn -type d | xargs tar -cvzf $OUTPUTDIR/SVNfiles-$VERSION.tar.gz 

svn export fpc fpc-$VERSION --native-eol CRLF
rm -f $OUTPUTDIR/$PACKNAME.tar.gz $OUTPUTDIR/$PACKNAME.zip
zip -D9r $OUTPUTDIR/$PACKNAME.zip fpc-$VERSION

rm -rf fpc-$VERSION
svn export fpc fpc-$VERSION
tar cfv - fpc-$VERSION/ | gzip > $OUTPUTDIR/$PACKNAME.tar.gz
cd ..
rm -rf buildsrc
