.TH chmcmd 1 "29 December 2008" "Free Pascal" "HTML help file compression tool"
.SH NAME
chmcmd \- The FPC Pascal unit dependency tracking program.

.SH SYNOPSIS

\fBchmcmd\fP <helpfileproject.hfp>

.SH Description

.B chmcmd
- creates a Compressed HTML help file (chm) using a XML file made 
with the TCHMProject class in the fpc unit chmfilewriter.pas

.SH SEE ALSO
.IP 
.BR  chmls (1)
.BR  fpc (1)
.BR  fpdoc (1)
.TH chmcmd 1 "29 December 2008" "Free Pascal" "HTML help file compression tool"
.SH NAME
chmcmd \- The FPC Pascal unit dependency tracking program.

.SH SYNOPSIS

\fBchmcmd\fP <helpfileproject.hfp>

.SH Description

.B chmcmd
- creates a Compressed HTML help file (chm) using a XML file made 
with the TCHMProject class in the fpc unit chmfilewriter.pas

.SH SEE ALSO
.IP 
.BR  chmls (1)
.BR  fpc (1)
.BR  fpdoc (1)
