.TH chmls 1 "29 December 2008" "Free Pascal" "Compressed HTML help file content viewer"
.SH NAME
chmls \- The FPC Pascal unit dependency tracking program.

.SH SYNOPSIS

\fBchmls\fP <filename.chm> [section number]

.SH Description

.B chmls
- lists the complete contents of a chm file

The section number can be 0 or 1 and is a filter to show only files contained
in the uncompressed section of a chm or the compressed section respectively.
When not specified files from both sections are shown.
.SH SEE ALSO
.IP 
.BR  chmcmd (1)
.BR  fpc (1)
.BR  fpdoc (1)
.TH chmls 1 "29 December 2008" "Free Pascal" "Compressed HTML help file content viewer"
.SH NAME
chmls \- The FPC Pascal unit dependency tracking program.

.SH SYNOPSIS

\fBchmls\fP <filename.chm> [section number]

.SH Description

.B chmls
- lists the complete contents of a chm file

The section number can be 0 or 1 and is a filter to show only files contained
in the uncompressed section of a chm or the compressed section respectively.
When not specified files from both sections are shown.
.SH SEE ALSO
.IP 
.BR  chmcmd (1)
.BR  fpc (1)
.BR  fpdoc (1)
