.TH chmls 1 "29 December 2010" "Free Pascal" "Compressed HTML help file utility"
.SH NAME
chmls \- The FPC Pascal CHM utility

.SH SYNOPSIS

\fBchmls\fP [options] [command] [command specific parameters]

.SH Description

The \fBchmls\fP utility performs several CHM related functions,
such as listing CHM file contents, extracting one file or the whole archive
and extracting special files. Archiving however is the domain of the
\fBchmcmd\fP utility

.SH Command

.TP
\fB list\fP <filename> [section number]
Shows contents of the archive's directory. The section number can be 0 or 1,
when no section number is specified, content from both sections is
displayed.

.TP
\fB extract\fP <chm filename> <filename to extract> [saveasname]
Extracts file "filename to get" from archive "filename", and, if 
specified, saves it to [saveasname]. 

.TP
\fB extractall\fP <chm filename> [directory]
Extracts all files from archive "filename" to directory "directory"

.TP
\fBunblockchm\fP <filespec1> [filespec2] ..
(Windows only) Mass unblocks (XPsp2+) the relevant CHMs. Multiple files
and wildcards allowed

.TP
\fBextractalias\fP <chmfilename> [basefilename] [symbolprefix]
Extracts context info from file "chmfilename"
to basefilename.h and basefilename.ali,
using symbols "symbolprefix" + contextnr

.TP
\fBextracttoc\fP <chmfilename> [filename]
Extracts the toc (mainly to check binary TOC)

.TP
\fBextractindex\fP <chmfilename> [filename]
Extracts the index (mainly to check binary index)

For backwards compatibility reasons, the list command is default.

.SH Options

.TP
.BI \-h,\ \-\-help
Show help text

.TP
.BI \-p,\ \-\-no\-page
Do not page list command output

.TP
.BI \-n,\ \-\-name\-only
Only show "name" column in list command output

.SH SEE ALSO
.IP 
.BR  chmcmd (1)
.BR  fpc (1)
.BR  fpdoc (1)
