.TH fpcmkcfg 1 "30 April 2008" "Free Pascal" "Free Pascal configuration maker"
.SH NAME
fpcmkcfg \- The Free Pascal configuration program.

.SH SYNOPSIS

.B fpcmkcfg [options]

.SH DESCRIPTION
makes a configuration file for the compiler.

.B fpcmkcfg
TO BE FILLED.

.SH USAGE

.B fpcmkcfg

.SH OPTIONS
fpcmkcfg has a small number of options to control it's behaviour:

.SH SEE ALSO
.IP 
.BR  fpcmake (1)
.BR  ppc386 (1)
.BR  make (1)
