.TH fpcsubst 1 "30 April 2008" "Free Pascal" "Free Pascal macro processor"
.SH NAME
fpcsubst \- The Free Pascal macro processing program.

.SH SYNOPSIS

.B fpcsubst [options]

.SH DESCRIPTION
Replaces some standard %XYZ% identifiers with a text, it's a macro
preprocessor.

.B fpcsubst
TO BE FILLED.

.SH USAGE

.B fpcsubst

.SH OPTIONS
fpcsubst has a small number of options to control it's behaviour:

.SH SEE ALSO
.IP 
.BR  fpcmake (1)
.BR  ppc386 (1)
.BR  make (1)
