.TH fppkg 1 "18 Nov 2005" "Free Pascal" "Free Pascal Packages Downloader"
.SH NAME
fppkg \- The Free Pascal Packages Download program.

.SH SYNOPSIS

.B fppkg [options]

.SH DESCRIPTION

.B fppkg
TO BE FILLED.

.SH USAGE

.B fppkg

.SH OPTIONS
fppkg has a small number of options to control it's behaviour:

.SH SEE ALSO
.IP 
.BR  fpcmake (1)
.BR  ppc386 (1)
.BR  make (1)
