.TH mkxmlrpc 1 "30 April 2008" "Free Pascal" "Free Pascal XML-RPC creator"
.SH NAME
mkxmlrpc \- The Free Pascal XML-RPC program.

.SH SYNOPSIS

.B mkxmlrpc [options]

.SH DESCRIPTION
Creates an XML-RPC wrapper for a pascal interface.

.B mkxmlrpc
TO BE FILLED.

.SH USAGE

.B mkxmlrpc

.SH OPTIONS
mkxmlrpc has a small number of options to control it's behaviour:

.SH SEE ALSO
.IP 
.BR  fpcmake (1)
.BR  ppc386 (1)
.BR  make (1)
