.TH rmcvsdir 1 "30 April 2008" "Free Pascal" "Free Pascal CVS tree cleaner"
.SH NAME
rmcvsdir \- The Free Pascal CVS tree cleaner program.

.SH SYNOPSIS

.B rmcvsdir [options]

.SH DESCRIPTION
Removes the CVS directories from a directory tree.

.B rmcvsdir
TO BE FILLED.

.SH USAGE

.B rmcvsdir

.SH OPTIONS
rmcvsdir has a small number of options to control it's behaviour:

.SH SEE ALSO
.IP 
.BR  fpcmake (1)
.BR  ppc386 (1)
.BR  make (1)
